import { registerLocaleData } from '@angular/common';
import localeEs from '@angular/common/locales/es';
import localePt from '@angular/common/locales/pt';
import { Injectable, computed, signal, inject } from '@angular/core';
import { AppLanguage } from './models';
import { StorageService } from './storage.service';

type TranslationTable = Record<string, string>;

registerLocaleData(localeEs, 'es');
registerLocaleData(localePt, 'pt-BR');

const en: TranslationTable = {
  language: 'Language', english: 'English', spanish: 'Spanish', portuguese: 'Português (Brasil)', home: 'Home', practice: 'Practice', history: 'History', settings: 'Settings', navigation: 'Main navigation',
  brandTag: 'ZOVIDOO', trainTitle: 'Train the way you listen.', trainBody: 'Short, focused musical exercises that sharpen your ear a little every day.', seeHow: 'See how it works', ready: 'I’m ready', nameTitle: 'What’s your name?', nameBody: 'We’ll use it to make your practice feel personal.', namePlaceholder: 'Your first name', start: 'Start training', starting: 'Starting audio…', soundNotice: 'Starting enables sound in your browser.', languageHint: 'Choose your language', listeningRefined: 'MUSICAL LISTENING, REFINED', personalPractice: 'PERSONAL PRACTICE', smallSessions: 'Small sessions', smallSessionsBody: 'Most exercises take under a minute.', headphones: 'Headphones help', headphonesBody: 'Hear every detail with a clearer soundstage.', private: 'Private by design', privateBody: 'Your progress stays on this device.',
  settingsTitle: 'Settings', appearance: 'Language & region', practiceGroup: 'Practice', dailyGoal: 'Daily goal', dailyGoalHelp: 'Questions to complete each day', reminders: 'Local reminders', dailyReminder: 'Daily reminder', reminderTime: 'Reminder time', data: 'Your data', exportData: 'Export data', importData: 'Import data', resetData: 'Reset all data', localTime: 'Local time', browserPermission: 'Uses your device’s notification permission.', unavailable: 'Not supported in this browser.', downloadBackup: 'Download a JSON backup', restoreBackup: 'Restore a JSON backup', resetHelp: 'Remove this device’s profile and history', privacy: 'Zovidoo keeps all practice data on this device.', notificationsUnavailable: 'Notifications are unavailable or permission was not granted.', restoreBackupTitle: 'Restore backup?', restoreBackupMessage: '{count} sessions will replace your local data.', cancel: 'Cancel', restore: 'Restore', backupRestored: 'Backup restored.', importFailed: 'Could not import this file.', resetTitle: 'Reset all local data?', resetMessage: 'This removes your profile, settings and practice history from this device.', reset: 'Reset',
  practiceLab: 'PRACTICE LAB', practiceTitle: 'What would you like to hear?', practiceIntro: 'Choose one skill, or let us pick a focused prompt for you.', quickPractice: 'QUICK PRACTICE', surprise: 'Surprise me', quickSubtitle: 'One short listening set', explore: 'Explore exercises',
  listeningLog: 'YOUR LISTENING LOG', historyTitle: 'History', historyIntro: 'Each completed set becomes part of your musical record.', emptyHistory: 'Your history will grow here.', emptyHistoryBody: 'Complete a quick practice to create your first entry.', startPracticing: 'Start practicing', minute: 'min',
  replay: 'Replay', listenClosely: 'Listen closely', exit: 'Exit exercise', rootPrompt: 'Which note is the root?', nowRoot: 'Now find the root', chordOf: 'Chord {current} of {total}', correct: 'Correct — nice listening.', incorrect: 'Not quite — listen again.', complete: 'SESSION COMPLETE', beautiful: 'Beautiful work.', completeBody: 'You completed {count} listening prompts.', completed: 'completed', mistakes: 'mistakes', practiceTime: 'practice time', practiceAgain: 'Practice again', backHome: 'Back home', pianoAnswers: 'Pitch class answers',
  today: 'Today', exercises: 'exercises', accuracy: 'accuracy', minutesTotal: 'minutes total', sessions: 'sessions', rhythm: 'Your rhythm', daysWeek: 'days this week', daysMonth: 'this month', less: 'Less', more: 'More', streak: 'day streak', best: 'best', streakBody: 'Show up, listen closely, grow.', quickPrompt: 'Keep your ear in tune', quickPrompts: '5 mixed listening prompts', level: 'LEVEL 1 · BEGINNER', foundation: 'Listening foundations', foundationBody: 'Pitch, intervals and familiar harmony.', heard: 'heard', goodMorning: 'Good morning', goodAfternoon: 'Good afternoon', goodEvening: 'Good evening', musician: 'Musician',
  exerciseProgression: 'Identify progression', exerciseProgressionDescription: 'Hear the complete progression and choose the complete chord sequence.', exerciseChordSymbol: 'Identify chord', exerciseChordSymbolDescription: 'Name one chord by its symbol: C, Bb, Cm or D7.', exerciseProgressionChords: 'Progression chords', exerciseProgressionChordsDescription: 'Listen to a progression, then identify each chord symbol.', exerciseNote: 'Identify note', exerciseNoteDescription: 'Recognize a single pitch class.', exerciseInterval: 'Identify interval', exerciseIntervalDescription: 'Measure the space between notes.', exerciseChord: 'Chord quality + root', exerciseChordDescription: 'Identify the quality first, then its root.', beginner: 'Beginner', easy: 'Easy',
  notePrompt: 'Which note did you hear?', intervalPrompt: 'Which interval did you hear?', chordQualityPrompt: 'What chord quality did you hear?', chordSymbolPrompt: 'Which chord did you hear?', progressionPrompt: 'Which chord progression did you hear?', progressionChordsPrompt: 'Identify each chord in the progression.', thatWas: 'That was {answer}.', intervalExplanation: '{interval} is {semitones} semitones.', chordExplanation: 'It is {root} {quality}.', progressionExplanation: 'The progression was {progression}.', major: 'Major', minor: 'Minor', diminished: 'Diminished', augmented: 'Augmented', minorThird: 'Minor 3rd', majorThird: 'Major 3rd', perfectFourth: 'Perfect 4th', perfectFifth: 'Perfect 5th', octave: 'Octave', majorSecond: 'Major 2nd', minorSixth: 'Minor 6th', majorSixth: 'Major 6th',
  historyNote: 'Note recognition', historyInterval: 'Intervals', historyChord: 'Chords', historyChordSymbol: 'Chord symbols', historyProgression: 'Progressions', historyProgressionChords: 'Progression chords',
};

const es: TranslationTable = {
  ...en,
  language: 'Idioma', spanish: 'Español', home: 'Inicio', practice: 'Práctica', history: 'Historial', settings: 'Ajustes', navigation: 'Navegación principal', trainTitle: 'Entrena como escuchas.', trainBody: 'Ejercicios musicales cortos y enfocados que afinan tu oído cada día.', seeHow: 'Ver cómo funciona', ready: 'Estoy listo', nameTitle: '¿Cómo te llamas?', nameBody: 'Usaremos tu nombre para personalizar tu práctica.', namePlaceholder: 'Tu nombre', start: 'Empezar a entrenar', starting: 'Iniciando audio…', soundNotice: 'Al empezar se activa el sonido en tu navegador.', languageHint: 'Elige tu idioma', listeningRefined: 'ESCUCHA MUSICAL, REFINADA', personalPractice: 'PRÁCTICA PERSONAL', smallSessions: 'Sesiones cortas', smallSessionsBody: 'La mayoría dura menos de un minuto.', headphones: 'Los auriculares ayudan', headphonesBody: 'Escucha cada detalle con mayor claridad.', private: 'Privado por diseño', privateBody: 'Tu progreso queda en este dispositivo.',
  settingsTitle: 'Ajustes', appearance: 'Idioma y región', practiceGroup: 'Práctica', dailyGoal: 'Meta diaria', dailyGoalHelp: 'Preguntas para completar cada día', reminders: 'Recordatorios locales', dailyReminder: 'Recordatorio diario', reminderTime: 'Hora del recordatorio', data: 'Tus datos', exportData: 'Exportar datos', importData: 'Importar datos', resetData: 'Restablecer datos', localTime: 'Hora local', browserPermission: 'Usa el permiso de notificaciones de tu dispositivo.', unavailable: 'No disponible en este navegador.', downloadBackup: 'Descargar una copia JSON', restoreBackup: 'Restaurar una copia JSON', resetHelp: 'Eliminar perfil e historial de este dispositivo', privacy: 'Zovidoo mantiene tus datos en este dispositivo.', notificationsUnavailable: 'Las notificaciones no están disponibles o no se concedió el permiso.', restoreBackupTitle: '¿Restaurar copia?', restoreBackupMessage: '{count} sesiones reemplazarán tus datos locales.', cancel: 'Cancelar', restore: 'Restaurar', backupRestored: 'Copia restaurada.', importFailed: 'No se pudo importar este archivo.', resetTitle: '¿Restablecer todos los datos?', resetMessage: 'Esto elimina tu perfil, ajustes e historial de práctica de este dispositivo.', reset: 'Restablecer',
  practiceLab: 'LABORATORIO DE PRÁCTICA', practiceTitle: '¿Qué te gustaría escuchar?', practiceIntro: 'Elige una habilidad o deja que elijamos un reto para ti.', quickPractice: 'PRÁCTICA RÁPIDA', surprise: 'Sorpréndeme', quickSubtitle: 'Una sesión breve de escucha', explore: 'Explorar ejercicios', listeningLog: 'TU REGISTRO DE ESCUCHA', historyTitle: 'Historial', historyIntro: 'Cada sesión completada forma parte de tu registro musical.', emptyHistory: 'Tu historial crecerá aquí.', emptyHistoryBody: 'Completa una práctica rápida para crear tu primera entrada.', startPracticing: 'Empezar a practicar', minute: 'min',
  replay: 'Repetir', listenClosely: 'Escucha con atención', exit: 'Salir del ejercicio', rootPrompt: '¿Cuál es la raíz?', nowRoot: 'Ahora encuentra la raíz', chordOf: 'Acorde {current} de {total}', correct: 'Correcto — buena escucha.', incorrect: 'Aún no — escucha otra vez.', complete: 'SESIÓN COMPLETA', beautiful: 'Buen trabajo.', completeBody: 'Completaste {count} ejercicios de escucha.', completed: 'completados', mistakes: 'errores', practiceTime: 'tiempo de práctica', practiceAgain: 'Practicar de nuevo', backHome: 'Volver al inicio', pianoAnswers: 'Respuestas de clases de nota',
  today: 'Hoy', exercises: 'ejercicios', accuracy: 'precisión', minutesTotal: 'minutos totales', rhythm: 'Tu ritmo', daysWeek: 'días esta semana', daysMonth: 'este mes', less: 'Menos', more: 'Más', streak: 'días seguidos', best: 'mejor', streakBody: 'Preséntate, escucha, crece.', quickPrompt: 'Mantén tu oído afinado', quickPrompts: '5 retos de escucha', level: 'NIVEL 1 · PRINCIPIANTE', foundation: 'Fundamentos de escucha', foundationBody: 'Tono, intervalos y armonía familiar.', heard: 'escuchados', goodMorning: 'Buenos días', goodAfternoon: 'Buenas tardes', goodEvening: 'Buenas noches', musician: 'Músico',
  exerciseProgression: 'Identificar progresión', exerciseProgressionDescription: 'Escucha la progresión completa y elige la secuencia de acordes.', exerciseChordSymbol: 'Identificar acorde', exerciseChordSymbolDescription: 'Nombra un acorde por su símbolo: C, Bb, Cm o D7.', exerciseProgressionChords: 'Acordes de progresión', exerciseProgressionChordsDescription: 'Escucha una progresión e identifica cada símbolo de acorde.', exerciseNote: 'Identificar nota', exerciseNoteDescription: 'Reconoce una única clase de nota.', exerciseInterval: 'Identificar intervalo', exerciseIntervalDescription: 'Mide la distancia entre notas.', exerciseChord: 'Calidad y raíz', exerciseChordDescription: 'Identifica primero la calidad y luego la raíz.', beginner: 'Principiante', easy: 'Fácil',
  notePrompt: '¿Qué nota escuchaste?', intervalPrompt: '¿Qué intervalo escuchaste?', chordQualityPrompt: '¿Qué calidad de acorde escuchaste?', chordSymbolPrompt: '¿Qué acorde escuchaste?', progressionPrompt: '¿Qué progresión de acordes escuchaste?', progressionChordsPrompt: 'Identifica cada acorde de la progresión.', thatWas: 'Era {answer}.', intervalExplanation: '{interval} tiene {semitones} semitonos.', chordExplanation: 'Es {root} {quality}.', progressionExplanation: 'La progresión era {progression}.', major: 'Mayor', minor: 'Menor', diminished: 'Disminuido', augmented: 'Aumentado', minorThird: 'Tercera menor', majorThird: 'Tercera mayor', perfectFourth: 'Cuarta justa', perfectFifth: 'Quinta justa', octave: 'Octava', majorSecond: 'Segunda mayor', minorSixth: 'Sexta menor', majorSixth: 'Sexta mayor',
  historyNote: 'Reconocimiento de notas', historyInterval: 'Intervalos', historyChord: 'Acordes', historyChordSymbol: 'Símbolos de acorde', historyProgression: 'Progresiones', historyProgressionChords: 'Acordes de progresión',
};

const ptBR: TranslationTable = {
  ...en,
  language: 'Idioma', spanish: 'Español', home: 'Início', practice: 'Praticar', history: 'Histórico', settings: 'Configurações', navigation: 'Navegação principal', trainTitle: 'Treine o jeito que você escuta.', trainBody: 'Exercícios musicais curtos e focados para afinar seu ouvido todos os dias.', seeHow: 'Ver como funciona', ready: 'Estou pronto', nameTitle: 'Como você se chama?', nameBody: 'Vamos usar seu nome para tornar a prática mais pessoal.', namePlaceholder: 'Seu primeiro nome', start: 'Começar a treinar', starting: 'Iniciando áudio…', soundNotice: 'Ao começar, o som será ativado no navegador.', languageHint: 'Escolha seu idioma', listeningRefined: 'ESCUTA MUSICAL, REFINADA', personalPractice: 'PRÁTICA PESSOAL', smallSessions: 'Sessões curtas', smallSessionsBody: 'A maioria dura menos de um minuto.', headphones: 'Fones ajudam', headphonesBody: 'Ouça cada detalhe com mais clareza.', private: 'Privado por padrão', privateBody: 'Seu progresso fica neste dispositivo.',
  settingsTitle: 'Configurações', appearance: 'Idioma e região', practiceGroup: 'Prática', dailyGoal: 'Meta diária', dailyGoalHelp: 'Perguntas para concluir por dia', reminders: 'Lembretes locais', dailyReminder: 'Lembrete diário', reminderTime: 'Horário do lembrete', data: 'Seus dados', exportData: 'Exportar dados', importData: 'Importar dados', resetData: 'Redefinir dados', localTime: 'Horário local', browserPermission: 'Usa a permissão de notificações do dispositivo.', unavailable: 'Não disponível neste navegador.', downloadBackup: 'Baixar cópia JSON', restoreBackup: 'Restaurar cópia JSON', resetHelp: 'Remover perfil e histórico deste dispositivo', privacy: 'Zovidoo mantém seus dados neste dispositivo.', notificationsUnavailable: 'As notificações não estão disponíveis ou a permissão não foi concedida.', restoreBackupTitle: 'Restaurar cópia?', restoreBackupMessage: '{count} sessões substituirão seus dados locais.', cancel: 'Cancelar', restore: 'Restaurar', backupRestored: 'Cópia restaurada.', importFailed: 'Não foi possível importar este arquivo.', resetTitle: 'Redefinir todos os dados?', resetMessage: 'Isso remove seu perfil, configurações e histórico de prática deste dispositivo.', reset: 'Redefinir',
  practiceLab: 'LABORATÓRIO DE PRÁTICA', practiceTitle: 'O que você quer ouvir?', practiceIntro: 'Escolha uma habilidade ou deixe a gente selecionar um desafio.', quickPractice: 'PRÁTICA RÁPIDA', surprise: 'Surpreenda-me', quickSubtitle: 'Uma sessão curta de escuta', explore: 'Explorar exercícios', listeningLog: 'SEU REGISTRO DE ESCUTA', historyTitle: 'Histórico', historyIntro: 'Cada sessão concluída passa a fazer parte do seu registro musical.', emptyHistory: 'Seu histórico vai crescer aqui.', emptyHistoryBody: 'Conclua uma prática rápida para criar seu primeiro registro.', startPracticing: 'Começar a praticar', minute: 'min',
  replay: 'Repetir', listenClosely: 'Ouça com atenção', exit: 'Sair do exercício', rootPrompt: 'Qual é a nota raiz?', nowRoot: 'Agora encontre a raiz', chordOf: 'Acorde {current} de {total}', correct: 'Correto — ótima escuta.', incorrect: 'Ainda não — ouça outra vez.', complete: 'SESSÃO CONCLUÍDA', beautiful: 'Belo trabalho.', completeBody: 'Você concluiu {count} exercícios de escuta.', completed: 'concluídos', mistakes: 'erros', practiceTime: 'tempo de prática', practiceAgain: 'Praticar novamente', backHome: 'Voltar ao início', pianoAnswers: 'Respostas de classes de nota',
  today: 'Hoje', exercises: 'exercícios', accuracy: 'precisão', minutesTotal: 'minutos totais', sessions: 'sessões', rhythm: 'Seu ritmo', daysWeek: 'dias nesta semana', daysMonth: 'neste mês', less: 'Menos', more: 'Mais', streak: 'dias seguidos', best: 'melhor', streakBody: 'Apareça, escute, evolua.', quickPrompt: 'Mantenha seu ouvido afinado', quickPrompts: '5 desafios de escuta', level: 'NÍVEL 1 · INICIANTE', foundation: 'Fundamentos da escuta', foundationBody: 'Notas, intervalos e harmonia familiar.', heard: 'ouvidos', goodMorning: 'Bom dia', goodAfternoon: 'Boa tarde', goodEvening: 'Boa noite', musician: 'Músico',
  exerciseProgression: 'Identificar progressão', exerciseProgressionDescription: 'Ouça a progressão completa e escolha a sequência de acordes.', exerciseChordSymbol: 'Identificar acorde', exerciseChordSymbolDescription: 'Nomeie um acorde pelo símbolo: C, Bb, Cm ou D7.', exerciseProgressionChords: 'Acordes da progressão', exerciseProgressionChordsDescription: 'Ouça uma progressão e identifique cada símbolo de acorde.', exerciseNote: 'Identificar nota', exerciseNoteDescription: 'Reconheça uma única classe de nota.', exerciseInterval: 'Identificar intervalo', exerciseIntervalDescription: 'Meça a distância entre notas.', exerciseChord: 'Qualidade e raiz', exerciseChordDescription: 'Identifique primeiro a qualidade e depois a raiz.', beginner: 'Iniciante', easy: 'Fácil',
  notePrompt: 'Qual nota você ouviu?', intervalPrompt: 'Qual intervalo você ouviu?', chordQualityPrompt: 'Qual qualidade de acorde você ouviu?', chordSymbolPrompt: 'Qual acorde você ouviu?', progressionPrompt: 'Qual progressão de acordes você ouviu?', progressionChordsPrompt: 'Identifique cada acorde da progressão.', thatWas: 'Era {answer}.', intervalExplanation: '{interval} tem {semitones} semitons.', chordExplanation: 'É {root} {quality}.', progressionExplanation: 'A progressão era {progression}.', major: 'Maior', minor: 'Menor', diminished: 'Diminuto', augmented: 'Aumentado', minorThird: 'Terça menor', majorThird: 'Terça maior', perfectFourth: 'Quarta justa', perfectFifth: 'Quinta justa', octave: 'Oitava', majorSecond: 'Segunda maior', minorSixth: 'Sexta menor', majorSixth: 'Sexta maior',
  historyNote: 'Reconhecimento de notas', historyInterval: 'Intervalos', historyChord: 'Acordes', historyChordSymbol: 'Símbolos de acorde', historyProgression: 'Progressões', historyProgressionChords: 'Acordes da progressão',
};

Object.assign(en, {
  earTraining: 'EAR TRAINING', instrument: 'Instrument', instrumentHelp: 'Choose the sound used for practice.', piano: 'Piano', acousticGuitar: 'Acoustic guitar', electricPiano: 'Electric piano', organ: 'Organ', vibraphone: 'Vibraphone', warmPad: 'Warm pad', marimba: 'Marimba', random: 'Random', historyQuick: 'Quick practice', skillLevel: 'Level {level} · {score}%', skillsCovered: '{count} skills covered', reminderOpenOnly: 'While Zovidoo stays open. Background reminders need Web Push.', updateAvailable: 'A new version is ready.', updateNow: 'Update',
});
Object.assign(es, {
  earTraining: 'ENTRENAMIENTO AUDITIVO', instrument: 'Instrumento', instrumentHelp: 'Elige el sonido usado en la práctica.', piano: 'Piano', acousticGuitar: 'Guitarra acústica', electricPiano: 'Piano eléctrico', organ: 'Órgano', vibraphone: 'Vibráfono', warmPad: 'Pad cálido', marimba: 'Marimba', random: 'Aleatorio', historyQuick: 'Práctica rápida', skillLevel: 'Nivel {level} · {score}%', skillsCovered: '{count} habilidades cubiertas', reminderOpenOnly: 'Mientras Zovidoo permanece abierto. Los recordatorios en segundo plano necesitan Web Push.', updateAvailable: 'Hay una nueva versión.', updateNow: 'Actualizar',
});
Object.assign(ptBR, {
  earTraining: 'TREINO AUDITIVO', instrument: 'Instrumento', instrumentHelp: 'Escolha o som usado na prática.', piano: 'Piano', acousticGuitar: 'Violão acústico', electricPiano: 'Piano elétrico', organ: 'Órgão', vibraphone: 'Vibrafone', warmPad: 'Pad quente', marimba: 'Marimba', random: 'Aleatório', historyQuick: 'Prática rápida', skillLevel: 'Nível {level} · {score}%', skillsCovered: '{count} habilidades trabalhadas', reminderOpenOnly: 'Enquanto o Zovidoo estiver aberto. Lembretes em segundo plano precisam de Web Push.', updateAvailable: 'Uma nova versão está pronta.', updateNow: 'Atualizar',
});

const translations: Record<AppLanguage, TranslationTable> = { en, es, 'pt-BR': ptBR };

@Injectable({ providedIn: 'root' })
export class TranslationService {
  private readonly storage = inject(StorageService);

  readonly language = signal<AppLanguage>(this.resolveLanguage());
  readonly locale = computed(() => this.language() === 'pt-BR' ? 'pt-BR' : this.language());

  constructor() { document.documentElement.lang = this.language(); }

  t(key: string, params: Record<string, string | number> = {}): string {
    return Object.entries(params).reduce((value, [name, replacement]) => value.replace(`{${name}}`, String(replacement)), translations[this.language()][key] ?? en[key] ?? key);
  }

  setLanguage(language: AppLanguage): void {
    this.language.set(language);
    this.storage.updateSettings({ language });
    document.documentElement.lang = language;
  }

  private resolveLanguage(): AppLanguage {
    const saved = this.storage.settings().language;
    if (saved) return saved;
    const browser = navigator.languages?.[0] ?? navigator.language ?? 'en';
    if (browser.toLowerCase().startsWith('pt')) return 'pt-BR';
    if (browser.toLowerCase().startsWith('es')) return 'es';
    return 'en';
  }
}
